/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/WawaOffice.glb
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import gsap from 'gsap';
import { useFrame } from '@react-three/fiber';

export const FLOOR_HEIGHT = 2.3;
export const NB_FLOORS = 3;

export const Office = (props) => {
  const { nodes, materials } = useGLTF('./models/WawaOffice.glb')

  const ref = useRef();
  const timeline = useRef();
  const libRef = useRef();
  const atticRef = useRef();

  const scroll = useScroll();

  useFrame(() => {
    timeline.current.seek( scroll.offset * timeline.current.duration() );
  })

  useLayoutEffect(() => {
    timeline.current = gsap.timeline();
  
    // VERTICAL ANIMATION
    timeline.current.to(
      ref.current.position,
      {
        duration: 2,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
      },
      0
    );

    // OFFICE ROTATION
    timeline.current.to(
      ref.current.rotation,
      { duration: 1, x:0, y: Math.PI / 6, z: 0 },
      0
    )

    timeline.current.to(
      ref.current.rotation,
      { duration: 1, x:0, y: -Math.PI / 6, z: 0 },
      1
    )

    // OFFICE MOVEMENT

    timeline.current.to(
      ref.current.position,
      { duration: 1, x: -1, z: 2 },
      0
    )
    
    timeline.current.to(
      ref.current.position,
      { duration: 1, x: 1, z: 2 },
      1
    )

    // LIBRARY FLOOR

    timeline.current.from(
      libRef.current.position,
      {
        duration: 0.5,
        x: -2
      },
      0.5
    );

    timeline.current.from(
      libRef.current.rotation,
      {
        duration: 0.5,
        y: -Math.PI / 2
      },
      0
    );

    // ATTIC
    timeline.current.from(
      atticRef.current.position,
      {
        duration: 1.5,
        y: 2,
      },
      0
    )

    timeline.current.from(
      atticRef.current.rotation,
      {
        duration: 0.5,
        y: Math.PI / 2
      },
      1
    );

    timeline.current.from(
      atticRef.current.position,
      {
        duration: 0.5,
        z: -2
      },
      1.5
    )
  }, [])

  return (
    <group
      {...props}
      dispose={null}
      ref={ref}
      position={[0.5, -1, -1]}
      rotation={[0, -Math.PI / 3, 0]}
    >
      <mesh geometry={nodes["01_office"].geometry} material={materials["01"]} />
      <group position={[0, 2.11, -2.23]}>
        <group ref={libRef}>
          <mesh
            geometry={nodes["02_library"].geometry}
            material={materials["02"]}
          />
        </group>
      </group>
      <group position={[-1.97, 4.23, -2.2]}>
        <group ref={atticRef}>
          <mesh
            geometry={nodes["03_attic"].geometry}
            material={materials["03"]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/WawaOffice.glb')
